<?xml version="1.0" encoding="utf-8"?><Database Name="HamiDiabetDB" Class="DataAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.16.32.33;Initial Catalog=HamiDiabetDB;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HamiDiabetDBConnectionString" Provider="System.Data.SqlClient" />
</Database>