<?xml version="1.0" encoding="utf-8"?><Database Name="jwtTestDB" Class="DataAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.16.32.33;Initial Catalog=jwtTestDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="jwtTestDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.userTbl" Member="userTbls">
    <Type Name="userTbl">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ticket" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="hashAccessToken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hashRefreshToken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>